### ISSUE TITLE
LAUNCH TASK CHECKLIST

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#116]
Here's the process, once we're ready:
* [x] work finished in the staging database (confirmation from @kissane / @tsl-lindsay)
* [x] make manual snapshot of staging db
* [x] restore from manual snapshot on staging to production db
* [x] update site domain name in production admin!!!
* [x] deploy from `master` branch of repo to production application
* [x] run `rebuild_index` for search on production
* [x] do some cache-flushing

**Comment by ryanpitts** [comment]
🌮 🌮 🌮
