### ISSUE TITLE
CSS fixin

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#92]
There are a bunch of small CSS things we'll need to sort out in the next couple of days—I'll start up a list here.

- [ ] h3/h4 discrepancies—we're seeing the orange h3s on some pages and gray on others, and there are some weird things with h4s as well, so we'll need to do some detective work— https://github.com/OpenNews/opennews-source/issues/83
- [ ] image captions are not being styled as they should be on the majority of in-article images, for reasons that presently elude me, and I will investigate tomorrow — this is now hangin out at https://github.com/OpenNews/opennews-source/issues/98
- [ ] some sundry list-item spacing things we're tracking during the audit, and which I need to spec out for a proper bug/fix— https://github.com/OpenNews/opennews-source/issues/100
- [x] I need to find the place where Ethan mentioned the border-enabling image class so I can apply that to a bunch of articles
- [x] I need to figure out how to apply it to cover images when needed as well
- [ ] our Q&A formats look a little odd in the new styles, and need some design and CSS love— https://github.com/OpenNews/opennews-source/issues/101

That's what I have so far, and tomorrow I can pull together some examples and ideally exact specs for all of them, and then touch base with @ryanpitts about very very cautiously approaching the Holy Ethanic CSS.

**Comment by ryanpitts** [comment]
@kissane here's the [border-enabling image class comment](https://github.com/OpenNews/opennews-source/issues/72#issuecomment-277086034). Basically we just need to add `.has-border` to any `img` tag.

**Comment by ryanpitts** [comment]
There's now an option to "Put a border on lead image" on the article admin pages. https://github.com/OpenNews/opennews-source/issues/80

**Comment by beep** [comment]
(If there’s anything I can do to help with any of these issues, please let me know!)

**Comment by kissane** [comment]
Thanks, @beep! I may hit you up for one of them. 

Closing this now as all the issues live separately and are going into the master list.

**Comment by ryanpitts** [comment]
@kissane do you still want me to apply the CSS updates in https://github.com/OpenNews/opennews-source/issues/83 ?
